<? // Check if the username exists...

// Check if the pin code is valid...

// Check if the authenticator code is valid...

// Create account...

json_output("success", "Helloooo2o".$_POST['pin'].$_POST['username']);

exit; ?>
