<? // Check if the username exists...

// Check if the pin code is valid...

// Check if the authenticator code is valid...

// Create account...

json_output("success", "Hellooooo".implode(array_keys($_POST)));

exit; ?>
